name: Build OpenFFBoard firmware

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
      - development
  pull_request:
    branches:
      - master
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build firmware
  Build_firmware:
    strategy:
        fail-fast: false
        matrix:
          target: ['F411RE', 'F407VG'] # Targets to build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - {uses: ./.github/actions/build-firmware, with: {target: '${{ matrix.target }}', path: 'Output'}}
      
      - uses: actions/upload-artifact@v2
        with:
          name: OpenFFBoard-Firmware-${{ matrix.target }}
          path: ./Firmware/Output
