name: Release OpenFFBoard firmware

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # pull_request:
  #   branches:
  #     - master
  #     - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build firmware
  jobs:
  compliance:
    uses: Ultrawipf/OpenFFBoard/.github/workflows/build-firmware.yml@master

    - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Firmware version ${{ github.ref }}
          body: "Changelog here"
          draft: true # Only do a draft so we have a change to manually review
                      # the release before it goes live.
          prerelease: false